apiVersion: skaffold/v2beta5
kind: Config
deploy:
  kubectl:
    manifests:
      - "infra/k8s/*.yaml"
build:
  local:
    push: false
  artifacts:
    - image: ticketing/auth
      context: auth
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "src/**/*.ts"
            dest: .
    - image: cygnetops/ticketing-client
      context: client
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: '**/*.js'
            dest: .
