apiVersion: skaffold/v2beta5
kind: Config
deploy:
  kubectl:
    manifests:
    - "infra/k8s/*.yaml"
build:
  local:
    push: false
  artifacts:
  - image: ticketing/auth
    context: auth
    docker:
      dockerfile: Dockerfile
    sync:
      manual:
      - src: "src/**/*.ts"
        dest: .
  - image: cygnetops/ticketing-client
    context: client
    docker:
      dockerfile: Dockerfile
    sync:
      manual:
      - src: '**/*.js'
        dest: .
  - image: fsohrabi047/ticketing-tickets
    context: tickets
    docker:
      dockerfile: Dockerfile
    sync:
      manual:
      - src: "src/**/*.ts"
        dest: .
  - image: fsohrabi047/ticketing-orders
    context: orders
    docker:
      dockerfile: Dockerfile
    sync:
      manual:
      - src: "src/**/*.ts"
        dest: .
  - image: fsohrabi047/ticketing-expiration
    context: expiration
    docker:
      dockerfile: Dockerfile
    sync:
      manual:
      - src: "src/**/*.ts"
        dest: .
  - image: fsohrabi047/ticketing-payments
    context: payments
    docker:
      dockerfile: Dockerfile
    sync:
      manual:
      - src: "src/**/*.ts"
        dest: .
